# Generated by Django 3.2.25 on 2024-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('shifts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='vehicles.Vehicle'),
        ),
    ]
