# Generated by Django 3.2.25 on 2024-10-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parqueadero', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('poliza', models.CharField(max_length=100)),
                ('fecha_vencimiento_poliza', models.DateField()),
                ('horario_atencion', models.JSONField()),
                ('atencion_cliente', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=200)),
                ('capacidad_espacios', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
