# Generated by Django 3.2.25 on 2024-10-13 23:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinginfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinginfo',
            name='logo',
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='atencion_cliente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='capacidad_espacios',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='fecha_vencimiento_poliza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='horario_atencion',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
