# Generated by Django 3.2.25 on 2024-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinginfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinginfo',
            name='capacidad_espacios',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='logo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='nit',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
