# Generated by Django 3.2.25 on 2024-10-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkinginfo', '0002_auto_20241013_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginfo',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
