# Generated by Django 3.2.25 on 2024-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='menu_permissions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='menu_permissions',
            field=models.CharField(blank=True, choices=[('gestion_usuarios', 'Gestión de Usuarios'), ('configuracion_sistema', 'Configuración de Sistema'), ('generacion_reportes', 'Generación de Reportes'), ('sistema', 'Sistema')], max_length=50),
        ),
    ]
