# Generated by Django 3.2.25 on 2024-09-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Moto'), ('car_student', 'Carro Estudiante'), ('motorcycle_student', 'Moto Estudiante')], max_length=20)),
                ('price_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_duration_fixed', models.PositiveIntegerField(blank=True, help_text='Duración máxima (en horas) para tarifas fijas', null=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
