# Generated by Django 3.2.25 on 2024-10-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_convenio', models.CharField(max_length=100, unique=True)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarifa', models.CharField(default='Tarifa Genérica', max_length=100, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Carro'), ('motorcycle', 'Moto'), ('bicycle', 'Bicicleta')], max_length=20)),
                ('price_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifas', to='tariffs.convenio')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
